/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author roger
 */
public class pontos extends javax.swing.JFrame {

    /**
     * Creates new form pontos
     */
    public pontos() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnResetar = new javax.swing.JButton();
        Vitoria = new javax.swing.JLabel();
        Derrota = new javax.swing.JLabel();
        Empate = new javax.swing.JLabel();
        Pedra = new javax.swing.JLabel();
        Papel = new javax.swing.JLabel();
        Tesoura = new javax.swing.JLabel();
        lblVitoriaPedra = new javax.swing.JLabel();
        lblVitoriaPapel = new javax.swing.JLabel();
        lblVitoriaTesoura = new javax.swing.JLabel();
        lblDerrotaPedra = new javax.swing.JLabel();
        lblDerrotaPapel = new javax.swing.JLabel();
        lblDerrotaTesoura = new javax.swing.JLabel();
        lblEmpatePedra = new javax.swing.JLabel();
        lblEmpatePapel = new javax.swing.JLabel();
        lblEmpateTesoura = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Resultados");

        btnResetar.setText("Resetar");

        Vitoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Vitoria.setText("Vitória");

        Derrota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Derrota.setText("Derrota");

        Empate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Empate.setText("Empate");

        Pedra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Pedra.setText("Pedra");

        Papel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Papel.setText("Papel");

        Tesoura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Tesoura.setText("Tesoura");

        lblVitoriaPedra.setText("0");

        lblVitoriaPapel.setText("0");

        lblVitoriaTesoura.setText("0");

        lblDerrotaPedra.setText("0");

        lblDerrotaPapel.setText("0");

        lblDerrotaTesoura.setText("0");

        lblEmpatePedra.setText("0");

        lblEmpatePapel.setText("0");

        lblEmpateTesoura.setText("0");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(173, 173, 173))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltar)
                        .addGap(18, 18, 18)
                        .addComponent(btnResetar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblVitoriaPedra, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Vitoria)
                                    .addComponent(lblVitoriaPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVitoriaTesoura, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Papel)
                                    .addComponent(Pedra)
                                    .addComponent(Tesoura))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDerrotaPedra, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Derrota)
                            .addComponent(lblDerrotaPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDerrotaTesoura, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Empate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmpatePedra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmpatePapel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmpateTesoura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vitoria)
                    .addComponent(Empate)
                    .addComponent(Derrota))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pedra)
                    .addComponent(lblVitoriaPedra)
                    .addComponent(lblEmpatePedra)
                    .addComponent(lblDerrotaPedra))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Papel)
                    .addComponent(lblVitoriaPapel)
                    .addComponent(lblEmpatePapel)
                    .addComponent(lblDerrotaPapel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tesoura)
                    .addComponent(lblVitoriaTesoura)
                    .addComponent(lblEmpateTesoura)
                    .addComponent(lblDerrotaTesoura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResetar)
                    .addComponent(btnVoltar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        jokenpo form = new jokenpo();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pontos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pontos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pontos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pontos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pontos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Derrota;
    private javax.swing.JLabel Empate;
    private javax.swing.JLabel Papel;
    private javax.swing.JLabel Pedra;
    private javax.swing.JLabel Tesoura;
    private javax.swing.JLabel Vitoria;
    private javax.swing.JButton btnResetar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblDerrotaPapel;
    private javax.swing.JLabel lblDerrotaPedra;
    private javax.swing.JLabel lblDerrotaTesoura;
    private javax.swing.JLabel lblEmpatePapel;
    private javax.swing.JLabel lblEmpatePedra;
    private javax.swing.JLabel lblEmpateTesoura;
    private javax.swing.JLabel lblVitoriaPapel;
    public javax.swing.JLabel lblVitoriaPedra;
    private javax.swing.JLabel lblVitoriaTesoura;
    // End of variables declaration//GEN-END:variables
}
